### ISSUE TITLE
issue importing

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dev-labs-bg/transitioner#1]
I get this:

![image](https://user-images.githubusercontent.com/5357526/33843549-5f8e4d42-dea6-11e7-9a73-6697bfd30dae.png)

**Comment by radoyankov** [comment]
I see 2 errors. A missing deploy.gradle file and an iml error. You shouldn't have a problem with the gradle file, since it's only for uploading a version. As for the missing iml files, just rebuild and it should be OK. I just uploaded the missing file so you can build without errors.

**Comment by AndroidDeveloperLB** [comment]
I tried to rebuild. Still same exact issues.

**Comment by AndroidDeveloperLB** [comment]
I tried to clone the repo again, still has issues:

![image](https://user-images.githubusercontent.com/5357526/33844665-9eb32aa8-dea9-11e7-8e7c-b9b9cbc74de8.png)

**Comment by radoyankov** [comment]
Alright, it's fixed now. Rebuild after pulling everything.

**Comment by AndroidDeveloperLB** [comment]
I get this now:

![image](https://user-images.githubusercontent.com/5357526/33845821-5dd26bee-dead-11e7-9b4d-bd68ef95fcee.png)

**Comment by radoyankov** [comment]
Rebuild the project, man. "Keep All" and then press the green hammer in the toolbox.

**Comment by AndroidDeveloperLB** [comment]
I've cloned the project. Choosing to rebuild does the same thing as cloning it. I didn't choose to remove.
Here, attached a video to show you that even if I try again, it still fails.
[ice_video_20171211-201819.zip](https://github.com/dev-labs-bg/transitioner/files/1548907/ice_video_20171211-201819.zip)

**Comment by radoyankov** [comment]
Try going to File > Settings > Android SDK > Android SDK Location > Edit, and installing anything missing from there.

**Comment by AndroidDeveloperLB** [comment]
Nothing is missing. I already have cloned other repos and made working projects.

I've now tried to update the project with this:

    classpath 'com.android.tools.build:gradle:3.0.1'

Now it works fine.

**Comment by AndroidDeveloperLB** [comment]
The sample itself has a few issues I've noticed, though:
1. The small rectangle doesn't go to the target position well:

![image](https://user-images.githubusercontent.com/5357526/33848949-d25087e4-deb7-11e7-9287-1c44079b238e.png)


2. touching outside of the bottom views is allowed, so I can move things more to the left, yet I can't make them reach their goal on the right. It also means the bottom views can be out of sync.

![image](https://user-images.githubusercontent.com/5357526/33848960-de448f50-deb7-11e7-85bd-e06f7ed1a01d.png)


3. changing screen orientation doesn't save the state of the views. Only the bottom views are saved. This means they can be out of sync.
